server:
  port: 8080
spring:
  application:
    name: profile-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/profile-service?authSource=admin
idp:
  url: http://localhost:8180
  client-secret: AAlViPSva71qJcH5hDwjKXEuO7LX01rh
  client-id: KeyclockApp